module.exports = {

    token: {
        address: "0x3b36cd8fF53C7E9A121209cAab4727e6196026B8",
        abi: [{
            "constant": true,
            "inputs": [],
            "name": "name",
            "outputs": [{
                "name": "",
                "type": "string"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": true,
            "inputs": [],
            "name": "totalSupply",
            "outputs": [{
                "name": "",
                "type": "uint256"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": true,
            "inputs": [{
                "name": "",
                "type": "uint256"
            }],
            "name": "approvedAcctsAddresses",
            "outputs": [{
                "name": "",
                "type": "address"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": true,
            "inputs": [],
            "name": "getApprovedAccounts",
            "outputs": [{
                "name": "",
                "type": "address[]"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": true,
            "inputs": [],
            "name": "decimals",
            "outputs": [{
                "name": "",
                "type": "uint8"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": false,
            "inputs": [{
                "name": "_value",
                "type": "uint256"
            }],
            "name": "burn",
            "outputs": [{
                "name": "success",
                "type": "bool"
            }],
            "payable": false,
            "stateMutability": "nonpayable",
            "type": "function"
        }, {
            "constant": true,
            "inputs": [{
                "name": "",
                "type": "address"
            }],
            "name": "approvedAccounts",
            "outputs": [{
                "name": "",
                "type": "bool"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": false,
            "inputs": [{
                "name": "target",
                "type": "address"
            }, {
                "name": "approved",
                "type": "bool"
            }],
            "name": "approveAccount",
            "outputs": [],
            "payable": false,
            "stateMutability": "nonpayable",
            "type": "function"
        }, {
            "constant": true,
            "inputs": [{
                "name": "",
                "type": "address"
            }],
            "name": "balanceOf",
            "outputs": [{
                "name": "",
                "type": "uint256"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": false,
            "inputs": [{
                "name": "target",
                "type": "address"
            }, {
                "name": "mintedAmount",
                "type": "uint256"
            }],
            "name": "mintToken",
            "outputs": [],
            "payable": false,
            "stateMutability": "nonpayable",
            "type": "function"
        }, {
            "constant": true,
            "inputs": [],
            "name": "owner",
            "outputs": [{
                "name": "",
                "type": "address"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": true,
            "inputs": [],
            "name": "symbol",
            "outputs": [{
                "name": "",
                "type": "string"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": false,
            "inputs": [{
                "name": "_to",
                "type": "address"
            }, {
                "name": "_value",
                "type": "uint256"
            }],
            "name": "transfer",
            "outputs": [],
            "payable": false,
            "stateMutability": "nonpayable",
            "type": "function"
        }, {
            "constant": false,
            "inputs": [{
                "name": "newOwner",
                "type": "address"
            }],
            "name": "transferOwnership",
            "outputs": [],
            "payable": false,
            "stateMutability": "nonpayable",
            "type": "function"
        }, {
            "inputs": [{
                "name": "initialSupply",
                "type": "uint256"
            }, {
                "name": "tokenName",
                "type": "string"
            }, {
                "name": "tokenSymbol",
                "type": "string"
            }, {
                "name": "decimalUnits",
                "type": "uint8"
            }, {
                "name": "centralMinter",
                "type": "address"
            }],
            "payable": false,
            "stateMutability": "nonpayable",
            "type": "constructor"
        }, {
            "anonymous": false,
            "inputs": [{
                "indexed": true,
                "name": "from",
                "type": "address"
            }, {
                "indexed": true,
                "name": "to",
                "type": "address"
            }, {
                "indexed": false,
                "name": "value",
                "type": "uint256"
            }],
            "name": "Transfer",
            "type": "event"
        }, {
            "anonymous": false,
            "inputs": [{
                "indexed": true,
                "name": "from",
                "type": "address"
            }, {
                "indexed": false,
                "name": "value",
                "type": "uint256"
            }],
            "name": "Burn",
            "type": "event"
        }, {
            "anonymous": false,
            "inputs": [{
                "indexed": false,
                "name": "target",
                "type": "address"
            }, {
                "indexed": false,
                "name": "frozen",
                "type": "bool"
            }],
            "name": "ApprovedFunds",
            "type": "event"
        }]
    },
    exchange: {
        address: "0x082907c38a9c0e332F13d6D4D9E86fdc8e47d805",
        abi: [{
            "constant": true,
            "inputs": [],
            "name": "tokenReward",
            "outputs": [{
                "name": "",
                "type": "address"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": true,
            "inputs": [{
                "name": "",
                "type": "address"
            }],
            "name": "balanceOf",
            "outputs": [{
                "name": "",
                "type": "uint256"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": true,
            "inputs": [],
            "name": "price",
            "outputs": [{
                "name": "",
                "type": "uint256"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "inputs": [{
                "name": "etherCostOfEachToken",
                "type": "uint256"
            }, {
                "name": "addressOfTokenUsedAsReward",
                "type": "address"
            }],
            "payable": false,
            "stateMutability": "nonpayable",
            "type": "constructor"
        }, {
            "payable": true,
            "stateMutability": "payable",
            "type": "fallback"
        }]
    },
    association: {
        address: "0x47278aa1db0dde0e68a9f865597c9ae1dc38e3c4",
        abi: [{
            "constant": true,
            "inputs": [{
                "name": "",
                "type": "uint256"
            }],
            "name": "proposals",
            "outputs": [{
                "name": "recipient",
                "type": "address"
            }, {
                "name": "amount",
                "type": "uint256"
            }, {
                "name": "description",
                "type": "string"
            }, {
                "name": "votingDeadline",
                "type": "uint256"
            }, {
                "name": "executed",
                "type": "bool"
            }, {
                "name": "proposalPassed",
                "type": "bool"
            }, {
                "name": "numberOfVotes",
                "type": "uint256"
            }, {
                "name": "proposalHash",
                "type": "bytes32"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": false,
            "inputs": [{
                "name": "proposalNumber",
                "type": "uint256"
            }, {
                "name": "transactionBytecode",
                "type": "bytes"
            }],
            "name": "executeProposal",
            "outputs": [],
            "payable": false,
            "stateMutability": "nonpayable",
            "type": "function"
        }, {
            "constant": true,
            "inputs": [],
            "name": "sharesTokenAddress",
            "outputs": [{
                "name": "",
                "type": "address"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": true,
            "inputs": [],
            "name": "numProposals",
            "outputs": [{
                "name": "",
                "type": "uint256"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": false,
            "inputs": [{
                "name": "sharesAddress",
                "type": "address"
            }, {
                "name": "minimumSharesToPassAVote",
                "type": "uint256"
            }, {
                "name": "minutesForDebate",
                "type": "uint256"
            }],
            "name": "changeVotingRules",
            "outputs": [],
            "payable": false,
            "stateMutability": "nonpayable",
            "type": "function"
        }, {
            "constant": true,
            "inputs": [],
            "name": "debatingPeriodInMinutes",
            "outputs": [{
                "name": "",
                "type": "uint256"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": true,
            "inputs": [],
            "name": "minimumQuorum",
            "outputs": [{
                "name": "",
                "type": "uint256"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": true,
            "inputs": [],
            "name": "owner",
            "outputs": [{
                "name": "",
                "type": "address"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": false,
            "inputs": [{
                "name": "_from",
                "type": "address"
            }, {
                "name": "_value",
                "type": "uint256"
            }, {
                "name": "_token",
                "type": "address"
            }, {
                "name": "_extraData",
                "type": "bytes"
            }],
            "name": "receiveApproval",
            "outputs": [],
            "payable": false,
            "stateMutability": "nonpayable",
            "type": "function"
        }, {
            "constant": false,
            "inputs": [{
                "name": "beneficiary",
                "type": "address"
            }, {
                "name": "weiAmount",
                "type": "uint256"
            }, {
                "name": "jobDescription",
                "type": "string"
            }, {
                "name": "transactionBytecode",
                "type": "bytes"
            }],
            "name": "newProposal",
            "outputs": [{
                "name": "proposalID",
                "type": "uint256"
            }],
            "payable": false,
            "stateMutability": "nonpayable",
            "type": "function"
        }, {
            "constant": false,
            "inputs": [{
                "name": "beneficiary",
                "type": "address"
            }, {
                "name": "etherAmount",
                "type": "uint256"
            }, {
                "name": "jobDescription",
                "type": "string"
            }, {
                "name": "transactionBytecode",
                "type": "bytes"
            }],
            "name": "newProposalInEther",
            "outputs": [{
                "name": "proposalID",
                "type": "uint256"
            }],
            "payable": false,
            "stateMutability": "nonpayable",
            "type": "function"
        }, {
            "constant": false,
            "inputs": [{
                "name": "proposalNumber",
                "type": "uint256"
            }, {
                "name": "supportsProposal",
                "type": "bool"
            }],
            "name": "vote",
            "outputs": [{
                "name": "voteID",
                "type": "uint256"
            }],
            "payable": false,
            "stateMutability": "nonpayable",
            "type": "function"
        }, {
            "constant": true,
            "inputs": [{
                "name": "proposalNumber",
                "type": "uint256"
            }, {
                "name": "beneficiary",
                "type": "address"
            }, {
                "name": "weiAmount",
                "type": "uint256"
            }, {
                "name": "transactionBytecode",
                "type": "bytes"
            }],
            "name": "checkProposalCode",
            "outputs": [{
                "name": "codeChecksOut",
                "type": "bool"
            }],
            "payable": false,
            "stateMutability": "view",
            "type": "function"
        }, {
            "constant": false,
            "inputs": [{
                "name": "newOwner",
                "type": "address"
            }],
            "name": "transferOwnership",
            "outputs": [],
            "payable": false,
            "stateMutability": "nonpayable",
            "type": "function"
        }, {
            "inputs": [{
                "name": "sharesAddress",
                "type": "address"
            }, {
                "name": "minimumSharesToPassAVote",
                "type": "uint256"
            }, {
                "name": "minutesForDebate",
                "type": "uint256"
            }],
            "payable": true,
            "stateMutability": "payable",
            "type": "constructor"
        }, {
            "payable": true,
            "stateMutability": "payable",
            "type": "fallback"
        }, {
            "anonymous": false,
            "inputs": [{
                "indexed": false,
                "name": "proposalID",
                "type": "uint256"
            }, {
                "indexed": false,
                "name": "recipient",
                "type": "address"
            }, {
                "indexed": false,
                "name": "amount",
                "type": "uint256"
            }, {
                "indexed": false,
                "name": "description",
                "type": "string"
            }],
            "name": "ProposalAdded",
            "type": "event"
        }, {
            "anonymous": false,
            "inputs": [{
                "indexed": false,
                "name": "proposalID",
                "type": "uint256"
            }, {
                "indexed": false,
                "name": "position",
                "type": "bool"
            }, {
                "indexed": false,
                "name": "voter",
                "type": "address"
            }],
            "name": "Voted",
            "type": "event"
        }, {
            "anonymous": false,
            "inputs": [{
                "indexed": false,
                "name": "proposalID",
                "type": "uint256"
            }, {
                "indexed": false,
                "name": "result",
                "type": "uint256"
            }, {
                "indexed": false,
                "name": "quorum",
                "type": "uint256"
            }, {
                "indexed": false,
                "name": "active",
                "type": "bool"
            }],
            "name": "ProposalTallied",
            "type": "event"
        }, {
            "anonymous": false,
            "inputs": [{
                "indexed": false,
                "name": "newMinimumQuorum",
                "type": "uint256"
            }, {
                "indexed": false,
                "name": "newDebatingPeriodInMinutes",
                "type": "uint256"
            }, {
                "indexed": false,
                "name": "newSharesTokenAddress",
                "type": "address"
            }],
            "name": "ChangeOfRules",
            "type": "event"
        }, {
            "anonymous": false,
            "inputs": [{
                "indexed": false,
                "name": "sender",
                "type": "address"
            }, {
                "indexed": false,
                "name": "amount",
                "type": "uint256"
            }],
            "name": "receivedEther",
            "type": "event"
        }, {
            "anonymous": false,
            "inputs": [{
                "indexed": false,
                "name": "_from",
                "type": "address"
            }, {
                "indexed": false,
                "name": "_value",
                "type": "uint256"
            }, {
                "indexed": false,
                "name": "_token",
                "type": "address"
            }, {
                "indexed": false,
                "name": "_extraData",
                "type": "bytes"
            }],
            "name": "receivedTokens",
            "type": "event"
        }]
    }
}